name: Tellpart
version: 0.0.3
main: bluescreen9.minecraft.bukkit.tellpart.Main
api-version: 1.19
description: 'A bukkit teleport plugin'
commands:
  tpt:
  tph:
  tpr:
  tpp:
  home: 
  back: 